"""
Accounts tab for the Financial Model GUI.
"""

import json
import tkinter as tk
from datetime import date
from decimal import Decimal
from tkinter import filedialog, messagebox, simpledialog, ttk

from sqlalchemy import select

from src.models.import_record import ImportRecord
from src.models.portfolio_snapshot import PortfolioSnapshot

from src.database import get_session
from src.database_init import initialize_database
from src.services.account_export_service import AccountExportService
from src.services.account_service import AccountService
from src.services.portfolio_service import PortfolioService
from src.services.portfolio_valuation_service import PortfolioValuationService
from src.gui.account_holdings_window import show_account_holdings


class AccountsTab(ttk.Frame):
    """Display and manage investment accounts."""

    def __init__(self, parent: tk.Misc) -> None:
        super().__init__(parent)

        self.columnconfigure(0, weight=1)
        self.rowconfigure(3, weight=1)

        self.account_type_var = tk.StringVar()
        self.include_in_portfolio_var = tk.BooleanVar(value=True)
        self._loading_account_settings = False

        self._build_ui()

        # Refresh automatically whenever the Portfolio tab completes an
        # update.  The event is generated by PortfolioTab after its database
        # transaction has completed.
        self.winfo_toplevel().bind(
            "<<PortfolioUpdated>>",
            self._on_portfolio_updated,
            add="+",
        )

        # Also refresh when the Accounts page is first displayed.
        self.bind("<Map>", self._on_accounts_mapped, add="+")

        self.after(100, self._load_accounts)

    def _build_ui(self) -> None:
        """Build the Accounts page."""

        ttk.Label(
            self,
            text="Accounts",
            font=("Segoe UI", 18, "bold"),
        ).grid(
            row=0,
            column=0,
            sticky="w",
            pady=(0, 15),
        )

        controls = ttk.Frame(self)
        controls.grid(
            row=1,
            column=0,
            sticky="ew",
            pady=(0, 6),
        )

        ttk.Button(
            controls,
            text="Refresh",
            command=self._load_accounts,
        ).pack(side="left")

        ttk.Button(
            controls,
            text="Rename Account",
            command=self._rename_account,
        ).pack(
            side="left",
            padx=(8, 0),
        )

        ttk.Button(
            controls,
            text="View Holdings",
            command=self._view_holdings,
        ).pack(
            side="left",
            padx=(8, 0),
        )

        ttk.Button(
            controls,
            text="Export Included Accounts",
            command=self._export_included_accounts,
        ).pack(
            side="left",
            padx=(8, 0),
        )

        compare = ttk.Frame(self)
        compare.grid(
            row=2,
            column=0,
            sticky="ew",
            pady=(0, 10),
        )

        ttk.Label(
            compare,
            text="Compare Snapshots:",
            font=("Segoe UI", 10, "bold"),
        ).pack(side="left")

        ttk.Label(compare, text="From:").pack(
            side="left",
            padx=(15, 4),
        )

        self.from_var = tk.StringVar()
        self.from_entry = ttk.Entry(
            compare,
            textvariable=self.from_var,
            width=12,
        )
        self.from_entry.pack(side="left")

        ttk.Label(compare, text="To:").pack(
            side="left",
            padx=(12, 4),
        )

        self.to_var = tk.StringVar()
        self.to_entry = ttk.Entry(
            compare,
            textvariable=self.to_var,
            width=12,
        )
        self.to_entry.pack(side="left")

        ttk.Button(
            compare,
            text="Compare",
            command=self._compare_snapshots,
        ).pack(
            side="left",
            padx=(10, 0),
        )

        ttk.Label(
            compare,
            text="YYYY-MM-DD",
        ).pack(
            side="left",
            padx=(8, 0),
        )

        frame = ttk.Frame(self)
        frame.grid(
            row=3,
            column=0,
            sticky="nsew",
        )
        frame.rowconfigure(0, weight=1)

        columns = (
            "brokerage",
            "account_number",
            "name",
            "account_type",
            "include",
            "current_value",
            "gain_loss",
            "roi",
            "cash",
            "holdings",
            "last_import",
        )

        self.accounts_tree = ttk.Treeview(
            frame,
            columns=columns,
            show="headings",
            selectmode="browse",
        )

        headings = {
            "brokerage": "Brokerage",
            "account_number": "Account Number",
            "name": "Name",
            "account_type": "Type",
            "include": "Include",
            "current_value": "Current Value",
            "gain_loss": "Gain/Loss",
            "roi": "ROI",
            "cash": "Cash",
            "holdings": "Holdings",
            "last_import": "Last Import",
        }

        widths = {
            "brokerage": 75,
            "account_number": 95,
            "name": 135,
            "account_type": 65,
            "include": 55,
            "current_value": 120,
            "gain_loss": 120,
            "roi": 65,
            "cash": 115,
            "holdings": 65,
            "last_import": 105,
        }

        for column in columns:
            self.accounts_tree.heading(
                column,
                text=headings[column],
            )
            self.accounts_tree.column(
                column,
                width=widths[column],
                minwidth=50,
                anchor=(
                    "center"
                    if column == "include"
                    else "w"
                    if column in {
                        "brokerage",
                        "account_number",
                        "name",
                        "account_type",
                        "cash",
                        "last_import",
                    }
                    else "e"
                ),
                stretch=False,
            )

        self.accounts_tree.grid(
            row=0,
            column=0,
            sticky="nsw",
        )

        # Today is rendered in a small Canvas beside the single authoritative
        # account Treeview.  This lets the Today values be coloured
        # independently without creating a second selectable Treeview.
        today_panel = ttk.Frame(frame, width=120)
        today_panel.grid(
            row=0,
            column=1,
            sticky="nsw",
        )
        today_panel.grid_propagate(False)
        today_panel.columnconfigure(0, weight=1)
        today_panel.rowconfigure(1, weight=1)

        self.today_heading = ttk.Label(
            today_panel,
            text="Today",
            anchor="e",
            font=("Segoe UI", 10, "bold"),
            padding=(4, 4),
        )
        self.today_heading.grid(row=0, column=0, sticky="ew")

        self.today_canvas = tk.Canvas(
            today_panel,
            width=120,
            highlightthickness=0,
            borderwidth=0,
        )
        self.today_canvas.grid(row=1, column=0, sticky="nsew")

        scrollbar = ttk.Scrollbar(
            frame,
            orient="vertical",
            command=self._scroll_account_table,
        )
        scrollbar.grid(
            row=0,
            column=2,
            sticky="ns",
        )

        self.accounts_tree.configure(
            yscrollcommand=self._account_tree_scrolled,
        )

        self.accounts_tree.bind(
            "<<TreeviewSelect>>",
            self._account_selected,
        )
        self.accounts_tree.bind(
            "<ButtonRelease-1>",
            self._toggle_include_from_click,
            add="+",
        )
        self.accounts_tree.bind(
            "<Double-1>",
            self._on_account_double_click,
            add="+",
        )
        self.accounts_tree.bind(
            "<MouseWheel>",
            self._on_tree_mousewheel,
        )
        self.today_canvas.bind(
            "<MouseWheel>",
            self._on_tree_mousewheel,
        )

        settings = ttk.LabelFrame(
            self,
            text="Account Settings",
            padding=(10, 8),
        )
        settings.grid(
            row=4,
            column=0,
            sticky="ew",
            pady=(8, 0),
        )

        ttk.Label(
            settings,
            text="Account Type:",
        ).pack(side="left")

        self.account_type_combo = ttk.Combobox(
            settings,
            textvariable=self.account_type_var,
            values=("", *AccountService.ACCOUNT_TYPES),
            state="readonly",
            width=12,
        )
        self.account_type_combo.pack(
            side="left",
            padx=(6, 18),
        )

        ttk.Button(
            settings,
            text="Save Account Settings",
            command=self._save_account_settings,
        ).pack(
            side="left",
            padx=(18, 0),
        )

        self.status_label = ttk.Label(
            self,
            text="",
        )
        self.status_label.grid(
            row=5,
            column=0,
            sticky="w",
            pady=(8, 0),
        )

    def _on_portfolio_updated(self, _event=None) -> None:
        """Refresh account values after a successful portfolio update."""
        self._load_accounts()

    def _on_accounts_mapped(self, event=None) -> None:
        """Refresh the Accounts page when it becomes visible."""
        if event is None or event.widget is self:
            self._load_accounts()

    def _load_accounts(self) -> None:
        """Load account summaries from the database."""

        try:
            initialize_database()
            session = get_session()

            try:
                summaries = AccountService(session).get_summaries()
                today = date.today()
                snapshots = session.scalars(
                    select(PortfolioSnapshot).where(
                        PortfolioSnapshot.account_id.is_not(None),
                        PortfolioSnapshot.snapshot_date == today,
                    )
                ).all()
                snapshot_by_account = {
                    snapshot.account_id: snapshot
                    for snapshot in snapshots
                }
            finally:
                session.close()

            for item in self.accounts_tree.get_children():
                self.accounts_tree.delete(item)
            self.today_canvas.delete("all")

            for summary in summaries:
                tags = ()

                snapshot = snapshot_by_account.get(summary.account_id)
                today_change, today_percent, gain_loss, roi = (
                    self._performance_from_snapshot(
                        snapshot,
                        summary.current_value,
                    )
                )

                today_text = (
                    "--"
                    if today_change is None
                    else (
                        f"{self._format_signed_currency(today_change)} "
                        f"({self._format_percent(today_percent)})"
                    )
                )

                self.accounts_tree.insert(
                    "",
                    "end",
                    iid=str(summary.account_id),
                    values=(
                        summary.brokerage_name,
                        summary.account_number,
                        summary.name,
                        summary.account_type or "--",
                        "☑" if summary.include_in_portfolio else "☐",
                        self._format_currency(summary.current_value),
                        self._format_signed_currency(gain_loss),
                        self._format_percent(roi),
                        self._format_cash(summary.cash_by_currency),
                        str(summary.holdings_count),
                        self._format_datetime(summary.last_import),
                    ),
                    tags=tags,
                )

                if today_change is None or today_change == 0:
                    today_color = "black"
                elif today_change > 0:
                    today_color = "green"
                else:
                    today_color = "red"

                self._draw_today_row(
                    row_index=len(self.today_canvas.find_withtag("today_row")),
                    text=today_text,
                    color=today_color,
                )

            self._update_today_canvas_scrollregion(len(summaries))

            self.status_label.configure(
                text=f"{len(summaries)} account(s)"
            )

        except Exception as exc:
            self.status_label.configure(text="Unable to load accounts.")
            messagebox.showerror(
                "Accounts",
                f"Unable to load accounts:\n\n"
                f"{type(exc).__name__}: {exc}",
            )

    def _account_tree_scrolled(self, first: str, last: str) -> None:
        """Keep the Today canvas vertically aligned with the account rows."""
        self._today_scroll_fraction = float(first)
        self._today_scroll_last = float(last)
        self._update_today_canvas_position()

    def _scroll_account_table(self, *args) -> None:
        """Scroll the account table and its Today display together."""
        self.accounts_tree.yview(*args)
        self._update_today_canvas_position()

    def _on_tree_mousewheel(self, event) -> str:
        """Scroll the account table from either the table or Today column."""
        units = -1 * int(event.delta / 120) if event.delta else 0
        if units:
            self.accounts_tree.yview_scroll(units, "units")
            self._update_today_canvas_position()
        return "break"

    def _draw_today_row(
        self,
        row_index: int,
        text: str,
        color: str,
    ) -> None:
        """Draw one Today value in the canvas."""
        row_height = 20
        y = row_index * row_height + (row_height / 2)
        self.today_canvas.create_text(
            116,
            y,
            text=text,
            fill=color,
            anchor="e",
            font=("Segoe UI", 9),
            tags=("today_row",),
        )

    def _update_today_canvas_scrollregion(self, row_count: int) -> None:
        """Set the Today canvas scroll region to match the account rows."""
        row_height = 20
        height = max(1, row_count * row_height)
        self.today_canvas.configure(scrollregion=(0, 0, 120, height))
        self._update_today_canvas_position()

    def _update_today_canvas_position(self) -> None:
        """Apply the Treeview's current vertical scroll position to Today."""
        if not hasattr(self, "_today_scroll_fraction"):
            return
        self.today_canvas.yview_moveto(self._today_scroll_fraction)

    @staticmethod
    def _performance_from_snapshot(
        snapshot: PortfolioSnapshot | None,
        current_value: Decimal,
    ) -> tuple[Decimal | None, Decimal | None, Decimal, Decimal]:
        """Return today's change, unrealized gain, and ROI from cached data."""
        if snapshot is None:
            return None, None, Decimal("0"), Decimal("0")

        today_change = (
            Decimal(str(snapshot.daily_change))
            if snapshot.daily_change is not None
            else None
        )

        if today_change is None:
            today_percent = None
        else:
            previous_value = Decimal(str(current_value)) - today_change
            today_percent = (
                today_change / previous_value * Decimal("100")
                if previous_value != 0
                else Decimal("0")
            )

        gain_loss = Decimal("0")
        cost_basis = Decimal("0")

        if snapshot.valuation_data:
            data = json.loads(snapshot.valuation_data)
            usd_to_cad = Decimal(str(snapshot.usd_to_cad or 0))

            for item in data.get("holdings", []):
                gain = item.get("unrealized_gain")
                market_value = item.get("market_value")
                if gain is None or market_value is None:
                    continue

                gain_value = Decimal(str(gain))
                market_value_cad = Decimal(str(market_value))
                currency = str(item.get("currency") or "CAD").upper()
                is_usd = (
                    currency == "USD"
                    or str(item.get("symbol", "")).endswith(":US")
                )

                # Cached market_value is already stored in CAD.  Brokerage
                # unrealized_gain remains in the holding's native currency,
                # so only the gain needs FX conversion for USD positions.
                if is_usd:
                    gain_value *= usd_to_cad

                gain_loss += gain_value
                cost_basis += market_value_cad - gain_value

        roi = (
            gain_loss / cost_basis * Decimal("100")
            if cost_basis != 0
            else Decimal("0")
        )

        return today_change, today_percent, gain_loss, roi

    def _selected_account_id(self) -> int | None:
        """Return the selected account ID."""

        selected = self.accounts_tree.selection()

        if not selected:
            return None

        return int(selected[0])

    def _toggle_include_from_click(self, event) -> str | None:
        """Toggle portfolio inclusion when the Include cell is clicked."""
        if self.accounts_tree.identify("region", event.x, event.y) != "cell":
            return None
        if self.accounts_tree.identify_column(event.x) != "#5":
            return None

        row_id = self.accounts_tree.identify_row(event.y)
        if not row_id or not self.accounts_tree.exists(row_id):
            return None

        values = list(self.accounts_tree.item(row_id, "values"))
        new_value = values[4] not in ("☑", "Yes", "True", "1")

        # Let Treeview finish its normal selection processing first.  The
        # database write is then queued so the mouse event itself remains
        # lightweight and cannot interfere with row selection/highlighting.
        self.after_idle(
            lambda account_id=int(row_id), value=new_value:
            self._persist_include_change(account_id, value)
        )
        return None

    def _persist_include_change(self, account_id: int, include: bool) -> None:
        """Persist an inline Include checkbox change."""
        if not self.accounts_tree.exists(str(account_id)):
            return
        try:
            session = get_session()
            try:
                values = self.accounts_tree.item(str(account_id), "values")
                account_type = values[3] if len(values) > 3 and values[3] else None
                AccountService(session).update_settings(
                    account_id=account_id,
                    account_type=account_type,
                    include_in_portfolio=include,
                )
            finally:
                session.close()

            values = list(self.accounts_tree.item(str(account_id), "values"))
            if len(values) >= 5:
                values[4] = "☑" if include else "☐"
                self.accounts_tree.item(str(account_id), values=values)

            self.event_generate("<<AccountSettingsChanged>>", when="tail")
        except Exception as exc:
            messagebox.showerror(
                "Account Settings",
                f"Unable to update portfolio inclusion:\n\n"
                f"{type(exc).__name__}: {exc}",
            )

    def _on_account_double_click(self, _event=None) -> None:
        """Open the selected account after Treeview selection has completed."""
        self.after_idle(self._view_holdings)

    def _account_selected(self, _event=None) -> None:
        """Load settings and snapshot dates for the selected account."""

        account_id = self._selected_account_id()

        if account_id is None:
            return

        try:
            initialize_database()
            session = get_session()

            try:
                account = AccountService(session).get(account_id)
                if account is not None:
                    self._loading_account_settings = True
                    self.account_type_var.set(account.account_type or "")
                    self.include_in_portfolio_var.set(
                        bool(account.include_in_portfolio)
                    )
                    self._loading_account_settings = False

                snapshots = session.scalars(
                    select(ImportRecord.snapshot_date)
                    .where(ImportRecord.account_id == account_id)
                    .order_by(ImportRecord.snapshot_date.desc())
                    .limit(2)
                ).all()
            finally:
                session.close()

            if len(snapshots) >= 2:
                self.to_var.set(self._format_date_value(snapshots[0]))
                self.from_var.set(self._format_date_value(snapshots[1]))
            elif len(snapshots) == 1:
                self.to_var.set(self._format_date_value(snapshots[0]))
                self.from_var.set(self._format_date_value(snapshots[0]))
            else:
                self.from_var.set("")
                self.to_var.set("")

        except Exception as exc:
            self.status_label.configure(
                text=(
                    "Unable to load snapshot dates: "
                    f"{type(exc).__name__}: {exc}"
                )
            )

    def _save_account_settings(self) -> None:
        """Persist the selected account's type and portfolio inclusion."""
        account_id = self._selected_account_id()

        if account_id is None:
            messagebox.showinfo(
                "Account Settings",
                "Select an account first.",
            )
            return

        try:
            initialize_database()
            session = get_session()

            try:
                AccountService(session).update_settings(
                    account_id=account_id,
                    account_type=self.account_type_var.get().strip() or None,
                    include_in_portfolio=self.include_in_portfolio_var.get(),
                )
            finally:
                session.close()

            self._load_accounts()
            self.accounts_tree.selection_set(str(account_id))
            self.accounts_tree.focus(str(account_id))

            self.status_label.configure(
                text="Account settings saved."
            )
            self.event_generate("<<AccountSettingsChanged>>", when="tail")

        except Exception as exc:
            messagebox.showerror(
                "Account Settings",
                f"Unable to save account settings:\n\n"
                f"{type(exc).__name__}: {exc}",
            )

    def _export_included_accounts(self) -> None:
        """Export all included accounts to CSV files."""
        output_directory = filedialog.askdirectory(
            title="Select Export Folder",
            parent=self,
        )

        if not output_directory:
            return

        try:
            initialize_database()
            session = get_session()

            try:
                paths = AccountExportService(session).export_included_accounts(
                    output_directory,
                )
            finally:
                session.close()

            account_file_count = len(paths)
            summary_created = any(
                path.name == "All_Accounts.csv"
                for path in paths
            )

            if summary_created:
                message = (
                    f"Export complete. {account_file_count - 1} account "
                    f"file(s) and All_Accounts.csv were created in:\n\n"
                    f"{output_directory}"
                )
            else:
                message = (
                    f"Export complete. {account_file_count} account file "
                    f"was created in:\n\n{output_directory}"
                )

            self.status_label.configure(text="Account export complete.")
            messagebox.showinfo("Export Accounts", message)

        except Exception as exc:
            messagebox.showerror(
                "Export Accounts",
                f"Unable to export accounts:\n\n"
                f"{type(exc).__name__}: {exc}",
            )

    def _compare_snapshots(self) -> None:
        """Compare the selected account between two snapshot dates."""

        account_id = self._selected_account_id()

        if account_id is None:
            messagebox.showinfo(
                "Compare Snapshots",
                "Select an account first.",
            )
            return

        try:
            first_date = self._parse_date(self.from_var.get())
            second_date = self._parse_date(self.to_var.get())

            if first_date > second_date:
                messagebox.showwarning(
                    "Compare Snapshots",
                    "From date must be on or before To date.",
                )
                return

            initialize_database()
            session = get_session()

            try:
                from src.services.portfolio_comparison_service import (
                    PortfolioComparisonService,
                )

                result = PortfolioComparisonService(session).compare(
                    first_date,
                    second_date,
                    account_id=account_id,
                )
            finally:
                session.close()

            account_values = self.accounts_tree.item(
                str(account_id),
                "values",
            )
            account_name = (
                str(account_values[2])
                if len(account_values) >= 3
                else ""
            )
            account_number = (
                str(account_values[1])
                if len(account_values) >= 2
                else str(account_id)
            )

            self._show_comparison(
                account_number=account_number,
                account_name=account_name,
                first_date=first_date,
                second_date=second_date,
                result=result,
            )

        except ValueError:
            messagebox.showwarning(
                "Compare Snapshots",
                "Enter dates using YYYY-MM-DD.",
            )
        except Exception as exc:
            messagebox.showerror(
                "Compare Snapshots",
                f"Unable to compare snapshots:\n\n"
                f"{type(exc).__name__}: {exc}",
            )

    def _show_comparison(
        self,
        account_number: str,
        account_name: str,
        first_date,
        second_date,
        result,
    ) -> None:
        """Display detailed snapshot comparison results."""

        title_name = (
            f" — {account_name}"
            if account_name and account_name != account_number
            else ""
        )

        window = tk.Toplevel(self)
        window.title(
            f"Snapshot Comparison - Account {account_number}{title_name}"
        )
        window.geometry("1450x650")
        window.minsize(1050, 500)

        window.columnconfigure(0, weight=1)
        window.rowconfigure(2, weight=1)

        ttk.Label(
            window,
            text=(
                f"Account {account_number}{title_name}    "
                f"{first_date:%Y-%m-%d} → {second_date:%Y-%m-%d}"
            ),
            font=("Segoe UI", 13, "bold"),
        ).grid(
            row=0,
            column=0,
            sticky="w",
            padx=15,
            pady=(15, 8),
        )

        summary = ttk.Frame(window)
        summary.grid(
            row=1,
            column=0,
            sticky="ew",
            padx=15,
            pady=(0, 10),
        )

        self._comparison_summary(
            summary,
            "From Value:",
            self._format_currency(result.first_value),
            0,
        )
        self._comparison_summary(
            summary,
            "To Value:",
            self._format_currency(result.second_value),
            2,
        )
        self._comparison_summary(
            summary,
            "Change:",
            self._format_signed_currency(result.value_difference),
            4,
        )

        active = [
            p for p in result.positions
            if p.first_quantity != 0 or p.second_quantity != 0
        ]

        ttk.Label(
            summary,
            text=f"Holdings: {len(active)}",
        ).grid(
            row=0,
            column=6,
            padx=(20, 0),
        )

        frame = ttk.Frame(window)
        frame.grid(
            row=2,
            column=0,
            sticky="nsew",
            padx=15,
            pady=(0, 10),
        )
        frame.columnconfigure(0, weight=1)
        frame.rowconfigure(0, weight=1)

        columns = (
            "symbol",
            "company",
            "q1",
            "q2",
            "dq",
            "a1",
            "a2",
            "mv1",
            "mv2",
            "g1",
            "g2",
            "status",
        )

        tree = ttk.Treeview(
            frame,
            columns=columns,
            show="headings",
        )

        headings = {
            "symbol": "Symbol",
            "company": "Company",
            "q1": "Qty From",
            "q2": "Qty To",
            "dq": "Qty Change",
            "a1": "Avg Cost From",
            "a2": "Avg Cost To",
            "mv1": "Market Value From",
            "mv2": "Market Value To",
            "g1": "Unrealized Gain From",
            "g2": "Unrealized Gain To",
            "status": "Status",
        }

        widths = {
            "symbol": 100,
            "company": 230,
            "q1": 90,
            "q2": 90,
            "dq": 100,
            "a1": 115,
            "a2": 115,
            "mv1": 140,
            "mv2": 140,
            "g1": 145,
            "g2": 145,
            "status": 100,
        }

        for column in columns:
            tree.heading(
                column,
                text=headings[column],
            )
            tree.column(
                column,
                width=widths[column],
                minwidth=70,
                stretch=False,
                anchor=(
                    "w"
                    if column in {"symbol", "company", "status"}
                    else "e"
                ),
            )

        tree.tag_configure("increase", foreground="green")
        tree.tag_configure("decrease", foreground="red")
        tree.tag_configure("neutral", foreground="black")

        for position in result.positions:
            tag = (
                "increase"
                if position.quantity_difference > 0
                else "decrease"
                if position.quantity_difference < 0
                else "neutral"
            )

            tree.insert(
                "",
                "end",
                values=(
                    position.symbol,
                    position.company_name,
                    self._format_quantity(position.first_quantity),
                    self._format_quantity(position.second_quantity),
                    self._format_signed_quantity(
                        position.quantity_difference
                    ),
                    self._format_currency(
                        position.first_average_cost
                    ),
                    self._format_currency(
                        position.second_average_cost
                    ),
                    self._format_currency(
                        position.first_market_value
                    ),
                    self._format_currency(
                        position.second_market_value
                    ),
                    self._format_signed_currency(
                        position.first_unrealized_gain
                    ),
                    self._format_signed_currency(
                        position.second_unrealized_gain
                    ),
                    position.status,
                ),
                tags=(tag,),
            )

        tree.grid(
            row=0,
            column=0,
            sticky="nsew",
        )

        scrollbar = ttk.Scrollbar(
            frame,
            orient="vertical",
            command=tree.yview,
        )
        scrollbar.grid(
            row=0,
            column=1,
            sticky="ns",
        )
        tree.configure(
            yscrollcommand=scrollbar.set,
        )

        ttk.Button(
            window,
            text="Close",
            command=window.destroy,
        ).grid(
            row=3,
            column=0,
            sticky="e",
            padx=15,
            pady=(0, 15),
        )

    @staticmethod
    def _comparison_summary(
        parent,
        label: str,
        value: str,
        column: int,
    ) -> None:
        ttk.Label(
            parent,
            text=label,
            font=("Segoe UI", 10, "bold"),
        ).grid(
            row=0,
            column=column,
            sticky="e",
        )
        ttk.Label(
            parent,
            text=value,
        ).grid(
            row=0,
            column=column + 1,
            sticky="w",
            padx=(5, 0),
        )

    @staticmethod
    def _parse_date(value: str):
        from datetime import datetime

        return datetime.strptime(
            value.strip(),
            "%Y-%m-%d",
        ).date()

    @staticmethod
    def _format_date_value(value) -> str:
        if hasattr(value, "date"):
            value = value.date()

        return value.strftime("%Y-%m-%d")

    def _rename_account(self) -> None:
        """Rename the selected account."""

        account_id = self._selected_account_id()

        if account_id is None:
            messagebox.showinfo(
                "Rename Account",
                "Select an account first.",
            )
            return

        values = self.accounts_tree.item(
            str(account_id),
            "values",
        )

        current_name = str(values[2])
        account_number = str(values[1])

        new_name = simpledialog.askstring(
            "Rename Account",
            f"Account {account_number}:",
            initialvalue=current_name,
            parent=self,
        )

        if new_name is None:
            return

        try:
            initialize_database()
            session = get_session()

            try:
                AccountService(session).rename(
                    account_id,
                    new_name,
                )
            finally:
                session.close()

            self._load_accounts()

        except Exception as exc:
            messagebox.showerror(
                "Rename Account",
                f"Unable to rename account:\n\n"
                f"{type(exc).__name__}: {exc}",
            )

    def _view_holdings(self) -> None:
        """Open the shared consolidated account detail window."""

        account_id = self._selected_account_id()

        if account_id is None:
            messagebox.showinfo(
                "Account Holdings",
                "Select an account first.",
            )
            return

        session = None

        try:
            initialize_database()
            session = get_session()

            portfolio = PortfolioService(session).get_latest_portfolio(account_id)

            if portfolio is None:
                messagebox.showinfo(
                    "Account Holdings",
                    "No imported portfolio exists for this account.",
                )
                return

            valuation_service = PortfolioValuationService(session)
            cached_values = valuation_service.get_cached_current_values(
                account_id
            )

            if cached_values is None:
                messagebox.showinfo(
                    "Account Holdings",
                    "No calculated portfolio valuation is available yet. "
                    "Click 'Update Portfolio' first.",
                )
                return

            (
                current_holdings,
                current_cash,
                current_total,
                current_daily_change,
            ) = cached_values

            values = self.accounts_tree.item(str(account_id), "values")
            account_number = str(values[1]) if len(values) > 1 else str(account_id)
            account_name = str(values[2]) if len(values) > 2 else ""

            show_account_holdings(
                self,
                account_number,
                account_name,
                portfolio,
                current_holdings,
                current_cash,
                current_total,
                current_daily_change,
            )

        except Exception as exc:
            messagebox.showerror(
                "Account Holdings",
                f"Unable to load account holdings:\n\n"
                f"{type(exc).__name__}: {exc}",
            )
        finally:
            if session is not None:
                session.close()

    @staticmethod
    def _format_signed_quantity(
        value: Decimal | None,
    ) -> str:
        """Format a signed security quantity."""

        if value is None:
            return "--"

        if value == 0:
            return "0"

        sign = "+" if value > 0 else "-"
        return sign + AccountsTab._format_quantity(abs(value))

    @staticmethod
    def _format_currency(
        value: Decimal | None,
    ) -> str:
        """Format a CAD value."""

        if value is None:
            return "--"

        return f"${value:,.2f}"

    @staticmethod
    def _format_signed_currency(
        value: Decimal | None,
    ) -> str:
        """Format a signed currency value."""

        if value is None:
            return "--"

        return f"{value:+,.2f}"

    @staticmethod
    def _format_quantity(
        value: Decimal | None,
    ) -> str:
        """Format a security quantity."""

        if value is None:
            return "--"

        if value == value.to_integral_value():
            return f"{int(value):,}"

        return f"{value:,.6f}".rstrip("0").rstrip(".")

    @staticmethod
    def _format_cash(
        cash_by_currency: dict[str, Decimal],
    ) -> str:
        """Format cash balances by currency."""

        if not cash_by_currency:
            return "--"

        parts = []

        for currency in sorted(cash_by_currency):
            parts.append(
                f"{currency} ${cash_by_currency[currency]:,.2f}"
            )

        return " / ".join(parts)

    @staticmethod
    def _format_percent(
        value: Decimal | None,
    ) -> str:
        """Format a percentage value."""

        if value is None:
            return "--"

        value = Decimal(str(value))
        return f"{value:+.2f}%"

    @staticmethod
    def _format_datetime(
        value,
    ) -> str:
        """Format the last import timestamp."""

        if value is None:
            return "--"

        return value.strftime("%Y-%m-%d %H:%M:%S")
